insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Civil Sevices Commission', 1, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Commission on Audit', 1, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Commission on Elections', 1, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Commission on Human Rights', 1, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office of the Ombudsman', 1, NULL, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Al-Amanah Islamic Investment Bank of the Philippines', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('APO Production Unit Inc.', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Aurora Pacific Economic Zone and Freeport Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Authority of the Freeport Area of Bataan', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bangko Sentral ng Pilipinas', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bases Conversion and Development Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Cagayan Special Economic Zone Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Cebu Port Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Center for International Trade Expositions and Missions Inc.', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Civil Aviation Authority of the Philippines', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Clark International Airport Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Credit Information Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Cultural Center of the Philippines', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Development Academy of the Philippines', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Duty Free Philippines Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Employees Compensation Commission', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Government Service Insurance System (GSIS)', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Home Development Mutual Fund (PAG-IBIG)', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Laguna Lake Development Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Land Bank of the Philippines', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Light Rail Transit Authority (LRTA)', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Local Water Utilities Administration', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Lung Center of the Philippines', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Mactan-Cebu International Airport Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Manila International Airport Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Metropolitan Waterworks and Sewerage System', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Dairy Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Development Company', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Electrification Administration', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Food Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Home Mortgage Finance Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Housing Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Irrigation Administration', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Kidney and Transplant Institute', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Power Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Tobacco Administration', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Transmission Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Natural Resources Development Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Nayong Pilipino Foundation Inc.', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('North Luzon Railways Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Occupational Safety and Health Center', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('People''s Television Network Inc.', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Aerospace Development Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Amusement and Gaming Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Center for Economic Development', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Charity Sweepstakes Office (PCSO)', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Children''s Medical Center', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Coconut Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Crop Insurance Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Deposit Insurance Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philipine Economic Zone Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Fisheries Development Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Guarantee Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Health Insurance Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Heart Center', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Institute for Development Studies', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Institute of Traditional and Alternative Health Care', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine International Trading Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine National Oil Company', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine National Railways', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Ports Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Postal Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Reclamation Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Retirement Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Research Institute', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Veterans Investment Development Corporation-Industrial Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Power Sector Assets and Liabilities Management Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Quedan and Rural Credit Guarantee Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Small Business Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Social Housing Finance Corporation', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Social Security System', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Southern Philippines Development Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Subic Bay Metropolitan Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Sugar Regulatory Administration', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Tourism Infrastructure and Enterprise Zone Authority', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Tourism Promotions Board', 2, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Zamboanga City Special Economic Zone Authority', 2, NULL, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office of the President', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office of the Vice President', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Presidential Communications Operations Office', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Agrarian Reform', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Agriculture', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Budget and Management', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Education', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Energy', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Environment and Natural Resources', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Finance', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Foreign Affairs', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Health', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Information and Communications Technology', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Interior and Local Government', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Justice', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Labor and Employment', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of National Defense', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Public Works and Highways', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Science and Technology', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Social Welfare and Development', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Tourism', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Trade and Industry', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Department of Transportation', 5, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Economic and Development Authority', 5, NULL, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Anti-Money Laundering Council', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Climate Change Commission', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Commission on Filipino Overseas', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Commission on Higher Education', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Commission on Filipino Language', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Dangerous Drugs Board', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Energy Regulatory Commission', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Games amd Amusement Board', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Governance Commission for GOCCs', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Housing and Land Use Regulatory Board', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Housing and Urban Development Coordinating Council', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Mindanao Development Authority', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Movie and Television Review and Classification Board', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Archives of the Philippines', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Commission for Culture and Arts', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Historical Commission of the Philippines', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Intelligence Coordinating Agency', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Library of the Philippines', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Security Council', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office of the Presidential Adviser on the Peace Process', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Optical Media Board', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Pasig River Rehabilitation Commission', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Drug Enforcement Agency', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Racing Commission', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Sports Commission', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Presidential Legislative Liaison Office', 7, NULL, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Presidential Management Staff', 7, NULL, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Manila Economic and Cultural Council', 6, 83, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Metropolitan Manila Development Authority', 6, 83, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Broadcast Services', 6, 85, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Communication Services', 6, 85, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('News and Information Bureau', 6, 85, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Information Agency', 6, 85, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Printing Office', 6, 85, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Radio-Television Malacanang', 6, 85, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Agrarian Legal Assistance', 6, 86, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Agrarian Reform Beneficiaries Development', 6, 86, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Land Tenure Improvement', 6, 86, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Agricultural Training Institute', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Agriculture and Fisheries Standards', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Fisheries and Aquatic Resources', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Animal Industry', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Agricultural Research', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Plant Industry', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Soil and Water Management', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Agriculture and Fisheries Engineering', 6, 87, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Carabao Center', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Rubber Research Institute', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Center for Postharvest Development and Mechanization', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Agriculture Credit Policy Council', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Fertilizer and Pesticide Authority', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Meat Inspection Service', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Council for Agriculture and Fisheries', 6, 87, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Fiber Industry Development Authority', 6, 87, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Budget and Management Bureau-A', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Budget and Management Bureau-B', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Budget and Management Bureau-C', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Budget and Management Bureau-D', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Budget and Management Bureau-E', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Budget and Management Bureau-F', 6, 88, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Local Government and Regional Coordination Bureau', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Budget Technical Bureau', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Administrative Service', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Budget Information and Training Service', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Corporate Planning and Management Service', 6, 88, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Finance Service', 6, 88, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Fiscal Planning and Reforms Bureau', 6, 88, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Internal Audit Service', 6, 88, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Information and Communications Technology Systems Service', 6, 88, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Legal Service', 6, 88, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Organization Position Classification and Compensation Bureau', 6, 88, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Systems and Productivity Improvement Bureau', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Government Procument Policy Board - Technical Support Office', 6, 88, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Procurement Service', 6, 88, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Government Electronic Procurement System', 6, 88, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Curriculum Development', 6, 89, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Education Assessment', 6, 89, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Learning Delivery', 6, 89, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Learning Resources', 6, 89, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Human Resource and Organizational Development', 6, 89, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Learner Support Services', 6, 89, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Book Development Board', 6, 89, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Council for Children''s Television', 6, 89, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Museum', 6, 89, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Early Childhood Care and Development Council', 6, 89, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine High School for the Arts', 6, 89, NOW());

--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Energy Policy and Planning Bureau', 6, 90, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Energy Resource Development Bureau', 6, 90, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Energy Utilization and Management Bureau', 6, 90, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Oil Industry Management Bureau', 6, 90, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Electric Power Industry Management Bureau', 6, 90, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Renewable Energy Management Bureau', 6, 90, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Ecosystems Research and Development Bureau', 6, 91, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Forest Management Bureau', 6, 91, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Land Management Bureau', 6, 91, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Biodiversity Management Bureau', 6, 91, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Environmental Management Bureau', 6, 91, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Mines and Geosciences Bureau', 6, 91, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Mapping and Resource Information Authority', 6, 91, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Palawan Council for Sustainable Development', 6, 91, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Water Resources Board', 6, 91, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Customs', 6, 92, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Internal Revenue', 6, 92, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Local Government Finance', 6, 92, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of the Treasury', 6, 92, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Privatization and Management Office', 6, 92, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Securities and Exchange Commission', 6, 92, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Central Board of Assessment Appeals', 6, 92, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Insurance Commission', 6, 92, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Tax Research Center', 6, 92, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Foreign Service Institute', 6, 93, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('UNESCO National Commission of the Philippine Secretariat', 6, 93, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Technical Cooperation Council of the Philippines', 6, 93, NOW());

--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Health Policy Development and Planning Bureau', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of International Health Cooperation', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Health Facilities Development Bureau', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Knowledge Management and Information Technology Service', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Local Health Systems Development', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Health Human Resource Development Bureau', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Voluntary Blood Services Program', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Disease Prevention and Control Bureau', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Health Promotion and Communication Service', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Epidemiology Bureau', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Health Facilities and Services Regulatory Bureau', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Quarantine', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Food and Drug Administration', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Health Facilities Enhancement Program', 6, 94, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Health Emergency Management Bureau', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Amang Rodriguez Medical Center', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Dr. Jose Fabella Memorial Hospital', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('East Avenue Medical Center', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Jose R. Reyes Memorial Medical Center', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Center for Mental Health', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Children''s Hospital', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Orthopedic Center', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Quirino Medical Center', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Research Institute for Tropical Medicine', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Rizal Medical Center', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('San Lazaro Hospital', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Tondo Medical Center', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Commission on Population', 6, 94, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Nutrition Council', 6, 94, NOW());

--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Infrastructure Management Bureau', 6, 95, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Cybersecurity Bureau', 6, 95, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('ICT Literacy and Competency Development Bureau', 6, 95, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Government Digital Transformation Bureau', 6, 95, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National ICT Planning Policy and Standards Bureau', 6, 95, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('ICT Industry Development Bureau', 6, 95, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Privacy Commission', 6, 95, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Telecommunications Commission', 6, 95, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Cybercrime Investigation and Coordinating Center', 6, 95, NOW());

--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Local Government Development', 6, 96, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Local Government Supervision', 6, 96, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office of Project Development Services', 6, 96, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Barangay Operations Office', 6, 96, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Local Government Academy', 6, 96, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Fire Protection', 6, 96, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Jail Management and Penology', 6, 96, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Commission on Muslim Filipinos', 6, 96, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Youth Commission', 6, 96, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Commission on Women', 6, 96, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine National Police', 6, 96, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Public Safety College', 6, 96, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Police Commission', 6, 96, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Corrections', 6, 97, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Immigration', 6, 97, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Land Registration Authority', 6, 97, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Bureau of Investigation', 6, 97, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office of the Government Corporate Counsel', 6, 97, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Parole and Probation Administration', 6, 97, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Public Attorney''s Office', 6, 97, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Presidential Commission on Good Government', 6, 97, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Board of Pardons and Parole', 6, 97, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office for Alternative Dispute Resolution', 6, 97, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office of the Solicitor General', 6, 97, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Local Employment', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Labor Relations', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Working Conditions', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Workers with Special Concerns', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('International Labor Affairs Bureau', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Reintegration Center for OFWs', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Institute for Labor Studies', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Conciliation and Mediation Board', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Maritime Polytechnic', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Overseas Workers Welfare Administration', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Overseas Employment Administration', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Labor Relations Commission', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Wages and Productivity Commission', 6, 98, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Professional Regulation Commission', 6, 98, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Armed Forces of the Philippines', 6, 99, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Air Force', 6, 99, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Army', 6, 99, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Navy', 6, 99, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('AFP Health Service Command', 6, 99, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Military Academy', 6, 99, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Presidential Security Group', 6, 99, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Government Arsenal', 6, 99, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Defense College of the Philippines', 6, 99, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office of Civil Defense', 6, 99, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Veterans Affairs Office', 6, 99, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Veterans Memorial Medical Center', 6, 99, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Construction', 6, 100, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Design', 6, 100, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Equipment', 6, 100, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Maintenance', 6, 100, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Quality and Safety', 6, 100, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Research and Standards', 6, 100, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Council for Agriculture Aquatic and Natural Resources Research and Development', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Council for Health Research and Development', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Council for Industry Energy and Emerging Technology Research and Development', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Academy of Science and Technology', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Research Council of the Philippines', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Advanced Science and Technology Institute', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Food and Nutrition Research Institute', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Forest Products Research and Development Institute', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Industrial Technology Development Institure', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Metal Industry Research and Development Center', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Nuclear Research Institute', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Textile Research Institute', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Atmospheric Geophysical and Astronomical Services Administration', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Institute of Volcanology and Seismology', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Science High School System', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Science Education Institute', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Science and Technology Information Institute', 6, 101, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Technology Application and Promotion Institute', 6, 101, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Policy Development and Planning Bureau', 6, 102, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Standard Bureau', 6, 102, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Disaster Response Management Bureau', 6, 102, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Social Technology Bureau', 6, 102, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Protective Services Bureau', 6, 102, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Social Welfare Institutional Development Bureau', 6, 102, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Community Programs and Services Bureau', 6, 102, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Anti-Poverty Commission', 6, 102, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Commission on Indigenous Peoples', 6, 102, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Presidentail Commission for the Urban Poor', 6, 102, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Council for the Welfare of Children', 6, 102, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Inter-Country Adoption Board', 6, 102, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Council for Disability Affairs', 6, 102, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Juvenile Justice and Welfare Council', 6, 102, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('National Parks Development Committee', 6, 103, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Intramuros Administration', 6, 103, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Commission on Sports Scuba Diving', 6, 103, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Competitiveness Bureau', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Philippine Standards', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Consumer Protection and Advocacy Bureau', 6, 104, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Fair Trade Enforcement Bureau', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Import Services', 6, 104, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of International Trade Relations', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Trade and Industrial Policy Research', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Accreditation Bureau', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Small and Medium Enterprise Development', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Bureau of Domestic Trade Promotion', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Export Marketing Bureau', 6, 104, NOW());
--insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Foreign Trade Service Corps', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Cooperative Development Authority', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Technical Education and Skills Development Authority', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Board of Investments', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Construction Insdustry Authority of the Philippines', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Design Center of the Philippines', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Intellectual Property Office of the Philippines', 6, 104, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Trade Training Center', 6, 104, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Land Transportation Office', 6, 105, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Land Transportation Franchising and Regulatory Board', 6, 105, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office of the Transport Security', 6, 105, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Coast Guard', 6, 105, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Civil Aeronautics Board', 6, 105, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Maritime Industry Authority', 6, 105, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Office of Transportation Cooperatives', 6, 105, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Toll Regulatory Board', 6, 105, NOW());

insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine National Volunteer Service Coordinating Agency', 6, 106, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Public-Private Partnership Center of the Philippines', 6, 106, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Statistics Authority', 6, 106, NOW());
insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Philippine Statistical Research and Training Institute', 6, 106, NOW());
-- insert into govtagency(agencyname, govtagencyclassid, parentgovagencyid, creationdate) values('Tariff Commission', 6, 106, NOW());