<?php
//this is the footer
?>
					</div>
				</div>
				</div>

				
			</div>

<script type="text/javascript">
(function(d, s, id) {
  var js, gjs = d.getElementById('gwt-standard-footer');

  js = d.createElement(s); js.id = id;
  js.src = "footer-source_data/footer.js";
  gjs.parentNode.insertBefore(js, gjs);
}(document, 'script', 'gwt-footer-jsdk'));
</script>

<!-- PST -->


<script type="text/javascript" src="js/backbone.min.js.download"></script>
<script type="text/javascript">
/* <![CDATA[ */
var wpApiSettings = {"root":"https:\/\/www.dap.edu.ph\/wp-json\/","nonce":"77d9c07ac2","versionString":"wp\/v2\/"};
/* ]]> */
</script>
<script type="text/javascript" src="js/api-request.min.js.download"></script>
<script type="text/javascript" src="js/wp-api.min.js.download"></script>
<script type="text/javascript" src="js/skip-link-focus-fix.js.download"></script>
<script type="text/javascript" src="js/theme.js.download"></script><div class="reveal-overlay"><div id="a11y-modal" class="reveal large" title="Accessibility Statement" data-reveal="2y37hx-reveal" role="dialog" aria-hidden="true" data-yeti-box="a11y-modal" data-resize="a11y-modal">
	<button class="close-button" data-close="" aria-label="Close modal" type="button">
		<span aria-hidden="true">×</span>
	</button>
</div></div>
<script type="text/javascript">
/* <![CDATA[ */
var SlimStatParams = {"ajaxurl":"https:\/\/www.dap.edu.ph\/wp-admin\/admin-ajax.php","extensions_to_track":"pdf,doc,xls,zip","outbound_classes_rel_href_to_not_track":"noslimstat,ab-item","ci":"YToxOntzOjEyOiJjb250ZW50X3R5cGUiO3M6NDoiaG9tZSI7fQ==.4238c2497d3107992abe72cd7727296a"};
/* ]]> */
</script>
<script type="text/javascript" src="js/wp-slimstat.min.js.download"></script>
<script type="text/javascript" src="js/wp-embed.min.js.download"></script>
</body></html>